# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: 
  name: CX-198

variables:
  - name: CCACHE_DIR
    value: /$(Pipeline.Workspace)/s/.ccache
  - name: CCACHE_LOGFILE
    value: $(Build.SourcesDirectory)/ccache.log

steps:
- script: |
    sudo apt update
    sudo apt install -y ccache
    export PATH="/usr/lib/ccache:$PATH"
    ccache -z # Reset ccache stats
  displayName: "Install and configure ccache"
- task: Cache@2
  inputs:
    key: 'ccache | "$(Agent.OS)" | **/*.cpp, **/*.h'
    path: $(CCACHE_DIR)
    cacheHitVar: CACHE_RESTORED
  displayName: "Cache ccache directory"
- script: |
    make
  workingDirectory: $(Build.SourcesDirectory)
  displayName: "Build with Makefile"
- script: |
    ccache -s # Show ccache stats
  displayName: "Show ccache stats"
- task: CollectCcacheStats@1
  inputs:
    ccacheLogFile: '$(Build.SourcesDirectory)/ccache.log'
    typeTag: 'ccache-test'